# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='short',
            field=models.CharField(default=b'', max_length=2),
        ),
    ]
